---
version: "3.8"

volumes:
  data:

# This docker-compose file is used to build and test the container
services:
  weewx:
    # Run the container normally
    image: felddy/weewx
    init: true
    restart: "no"
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - TIMEZONE=US/Eastern
      - WEEWX_UID=weewx
      - WEEWX_GID=dialout


  weewx-version:
    # Run the container to collect version information
    image: felddy/weewx
    init: true
    restart: "no"
    command: --version
